---
- name: Configure application
  hosts: all
  become: true
  become_method: sudo
  vars:
    application: travelplanet2
    repository_url: https://github.com/TomaszMolenda/travelplanet.git
    repository_path: "/home/tomo/{{ application }}"

  tasks:
    - name: Install packages
      apt: 
        update_cache: yes
        state: present
        name: "{{ packages }}"
      vars:
        packages:
          - git
          - python-pip
          - nginx
          - python-flask

    - name: Clone repository
      git:
        repo: "{{ repository_url }}"
        dest: "{{ repository_path }}"
        force: yes
        
    - name: Install requirements in virtualenv
      pip:
        requirements: "{{ repository_path }}/requirements.txt"
        virtualenv: "{{ repository_path }}/{{ application }}env"
    
    - name: Copy Upstart configuration
      template: 
        src: travelplanet-service.j2
        dest: "/etc/systemd/system/{{ application }}.service"

    - name: Make sure our server is running
      service: 
        name: "{{ application }}"
        state: started
        
    - name: Change permission
      file: 
        dest: "{{ repository_path }}"
        owner: "tomo"
        group: "tomo"
        mode: 0775
        recurse: yes
        
    - name: Copy Nginx site
      template:
        src: travelplanet-nginx.j2
        dest: "/etc/nginx/sites-enabled/{{ application }}"
      notify:
        - restart nginx

    - name: Make sure nginx is running
      service:
        name: nginx
        state: started

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
